### PR TITLE
Add TypeScript typings

### PR DESCRIPTION
**Pull request by zorji**
I use err-code for TypeScript and it's been very convenient for me. I would like it to have the builtin TypeScript type.

### CODE REVIEW

**Comment by wemeetagain** [comment]
bump

**Review by vasco-santos — APPROVED** [review]
LGTM!

**Comment by satazor** [comment]
Hello @wemeetagain,

Thanks for the PR but I will have to close it as I’m not in favor of adding typescript types:

- One more file/piece to maintain
- The library isn’t done in typescript
- I usually don’t use typescript
- You can publish this library types to @types, see https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

Sorry, hope you understand.

**Comment by zorji** [comment]
@satazor No problems, I can contribute this to @types.

Do you want me add you as a maintainer of the types? or are you fine for me to just put my name? See https://github.com/DefinitelyTyped/DefinitelyTyped#definition-owners

**Comment by wemeetagain** [comment]
@zorji I'm willing to help maintain. Will you make the PR soon? I'm planning on using these types soon/now.

**Comment by zorji** [comment]
> @zorji I'm willing to help maintain. Will you make the PR soon? I'm planning on using these types soon/now.

sweet I'll create one now

**Comment by zorji** [comment]
@wemeetagain PR is created here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45504

**Comment by zorji** [comment]
@wemeetagain err-code provide official type since v3.0.0, I've created a PR to remove it in @types https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52518

**Pull request closed without merging**
